export const UNIVERSITIES = [
  "Harvard University",
  "Stanford University",
  "MIT",
  "Yale University",
  "Princeton University",
  "Columbia University",
  "University of Chicago",
  "Duke University",
  "Northwestern University",
  "Caltech",
  "Johns Hopkins University",
  "Dartmouth College",
  "Brown University",
  "Cornell University",
  "Rice University",
  "Vanderbilt University",
  "University of Pennsylvania",
  "University of Notre Dame",
  "Georgetown University",
  "University of California, Berkeley",
  "UCLA",
  "University of Michigan",
  "University of Virginia",
  "Carnegie Mellon University",
  "University of Southern California",
  "New York University",
  "Boston University",
  "University of Texas at Austin",
  "University of Washington",
  "University of Wisconsin-Madison",
  "Ohio State University",
  "Penn State University",
  "University of Florida",
  "University of Illinois Urbana-Champaign",
  "Georgia Tech",
  "University of North Carolina at Chapel Hill",
  "University of Arizona",
  "Arizona State University",
  "University of Colorado Boulder",
  "University of Maryland",
  "Indiana University",
  "Purdue University",
  "University of Minnesota",
  "Rutgers University",
  "University of Pittsburgh",
  "University of Oregon",
  "University of Iowa",
  "University of Kansas",
  "University of Oklahoma",
  "Other",
] as const;

export type University = typeof UNIVERSITIES[number];
